### PR TITLE
fix: correct logic for startTime in trx-generator.ts

### PR DESCRIPTION
**Pull request by ssundahl**
fix startTime

### CODE REVIEW

**Comment by no23reason** [comment]
Thank you for the fix, can you please change the commit message so that it follows semantic commit message? This is necessary for the automatic release job to work properly. Please see [CONTRIBUTING.md](https://github.com/no23reason/jest-trx-results-processor/blob/master/CONTRIBUTING.md) for tools that can help you.

**Comment by ssundahl** [comment]
Is the commit message okay now?

**Comment by no23reason** [comment]
You updated just the name of the Pull Request (to a correct format), but you also need to change the commit itself to the same value too. Please see https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend for how to do that

**Comment by ssundahl** [comment]
I think it's correct.  Not sure why I tried using the web interface from the beginning rather than the command line.

**Review by no23reason — APPROVED** [review]

**Pull request merged**
